### ISSUE TITLE
XFDSN: to FDSN: 

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#10]
Placeholder issue, drop the 'X' in `XFDSN:` if/when spec is approved by FDSN. The prefix should be just `FDSN:`

**Comment by chad-earthscope** [comment]
The original thinking for the `X` was two fold:

- There could be an `FDSN:NET_STA_LOC_CHAN` identifier with the SEED 2.4 code limitations
- The `X` makes clear that a reader should expect potentially larger codes than defined SEED 2.4

but I admit that another identifier may not be worth it, and the clarifying difference may not be justified.

So, I'm fine with simply `FDSN:` as this will be the first such identifier it should be clear which specification defines it.

**Comment by crotwell** [comment]
Thinking about this, I feel like the lengths of each piece are sufficient and the X is not needed. Basically, if length of the net is 1-2, station is <=5, loc is 0 or 2 and channel is 3, then it is also an old style SEED 2.4 identifier. If not, then it isn't. 

I vote to drop the X and just use FDSN:

**Comment by chad-earthscope** [comment]
This was done in cf35c47327b39f5f8fcf8f64ffe1e978b403b638
