### ISSUE TITLE
Network and station identifier addition

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#11]
Perhaps put into the spec that a station can be identified with:
```
XFDSN:<network>_<station>
```
and similarly a network by
```
XFDSN:<network>
```

**Comment by chad-earthscope** [comment]
I really like this concept and had planned on using it.  I think there are some dragons in there that may not be obvious yet, like how would an arbitrary system know that the identifier no longer refers to a unique time series source.   Problem?

**Comment by crotwell** [comment]
Would it be enough for those to not be "data source identifiers," but something else?

Alternative could be something like
```
XFDSN:STA:<network>_<station>

XFDSN:NET:<network>
```
if you are worried that lack of underscores is not sufficient to differentiate?

I am fine with deferring this, just seemed a nice extension of the channel identifier idea.

**Comment by chad-earthscope** [comment]
I don't necessarily think we should defer, this is the right time to include such an idea so that it can be consistently used.

Interesting alternate idea, more complicated for readers though.   Perhaps the lack of underscores is sufficient though, and simple truncation _is_ the obvious thing to do.  

For now, I vote to go with the original idea of specifying that truncated identifiers are the suggested way to identify networks, stations and locations, i.e.:

```
XFDSN:<network>
XFDSN:<network>_<station>
XFDSN:<network>_<station>_<location>
```

**Comment by flofux** [comment]
I can't really tell which is the best solution from a code point of view. But certainly users need to have a wave to identify an entire network or a station including all channels. The documentation does not seem very clear about this at the moment ...

**Comment by crotwell** [comment]
Propose add/change spec in `Identifiers as a URN` section:

```
The xFDSN identifier is a combination of the network, station, location, band, source 
and position codes into a Uniform Resource Name (URN) as defined by RFC 3986. The 
pattern of the source identifier URN is as follows:

For identifying a network:

XFDSN:<network>

For identifying a station within a network:

XFDSN:<network>_<station>

For identifying a location group, ie collection of specific channels within a station:

XFDSN:<network>_<station>_<location>

For identifying a data source, ie specific channel:

XFDSN:<network>_<station>_<location>_<band>_<source>_<position>
```

**Comment by chad-earthscope** [comment]
I've simplified this earlier proposed section text:
http://docs.fdsn.org/projects/source-identifiers/en/draft/definition.html#identifiers-as-a-urn

Reasons: I think it's most important to see the full pattern right away and it was buried.  Also, it was just longer than seemed to be needed.

Reopening to make sure @crotwell and others are OK with this.

**Comment by crotwell** [comment]
Yep, that is an improvement.
+1
