### ISSUE TITLE
Include description of mapping between SID and N, S, L, C components w/ exception for channel

### ISSUE THREAD

**Issue by chad-earthscope** [FDSN/source-identifiers#12]
I suggest that we add a paragraph to describe mapping between SIDs and SEED Network, Station, Location and Channel identifiers.  Constructing an SID from NSLC components is described in the definition, strongly implying the reverse, but this could/should be explicitly described.  In particular the potential for SID sub-components to be larger than allowed than their SEED same-named counterparts, and thus not usable in SEED 2 formats.

Further, a suggestion that implementors parsing an SID should collapse the "Channel" codes by removing the underscores when they are exactly 3 characters in order to create SEED 2 compatible codes whenever possible.  For example, an SID may be specified as:

```
XFDSN:XX_STA_LO_B_H_Z
```
and when parsed/decomposed into Network, Station, Location and Channel results in a channel of `BHZ`.  This, of course, will be required when mapping such identifiers to older SEED 2 systems, and the suggestion is to codify it as normal practice.

**Comment by crotwell** [comment]
Propose add section to "Definition of identifiers":


Transitional mapping of SEED2.4 identifiers

Within SEED2.4 <add reference url?>, data sources are identified by a combination of network, station, location and
channel codes, referred to as a NSLC. A NSLC may be mapped to an FDSN identifier without loss. So long as each item is within the
length restrictions imposed by SEED 2.4, these can be also be mapped from XFDSN identifiers back to NSLC.  The
mapping is as follows:

From NSLC to XFDSN:

Network:

For permanent networks, the 1-2 character network code is mapped unchanged.

For temporary networks, the 2 character network code may be mapped either unchanged, or may follow the "Transitional mapping of previously allocated temporary network codes" by appending the start year to create a 6 character code.

For Stations:

The 1-5 character station code is mapped unchanged. 

For Location codes:

The 0-2 character location code is mapped unchanged.

For Channel codes:

The 3 character SEED2.4 Channel code is split into the three single character band, instrument and orientation characters and these are mapped to the XFDSN band, source and subsource codes. 

Examples:
Permanent network NSLC: 'IU', 'ANMO', '00', 'BHZ' maps to XFDSN:IU_ANMO_00_B_H_Z
Permanent network NSLC: 'IU', 'ANMO', '', 'BHZ' maps to XFDSN:IU_ANMO__B_H_Z
Temporary network starting in 2002 NSLC: 'XA', 'ABCD', '00', 'BHZ' maps to XFDSN:XA_ABCD_00_B_H_Z or to XFDSN:XA2002_ABCD_00_B_H_Z

From XFDSN to NSLC:


Network:

For permanent networks where the network code is 1-2 characters, it is mapped unchanged. 

For temporary networks following the "Temporary network codes convention", the first 2 characters of the network code mapped to the NSLC network code by removing the 4 character year.

For temporary networks not following the "Temporary network codes convention", but with a 2 character network code, the code is mapped unchanged.

For networks with a network code greater than 2 characters, mapping is not supported.

For Station codes:

For stations with where the station code is 1-5 characters, it is mapped unchanged. 

For stations with a network code greater than 5 characters, mapping is not supported.

For Location codes:

For locations with where the location code is 0 or 2 characters, it is mapped unchanged. 

For locations with a location code of 1 character or greater than 2 characters, mapping is not supported.

For Channel codes:

For channels with where the XFDSN band, source and subsource codes are all 1 characters, the 3 characters are concatenated in this order and mapped to the 3 character NSLC channel code. 

For channels with where the XFDSN band, source and subsource codes are not all 1 characters, mapping is not supported.

Examples:

Permanent network  XFDSN:IU_ANMO_00_B_H_Z maps to NSLC: 'IU', 'ANMO', '00', 'BHZ' 
Permanent network XFDSN:IU_ANMO__B_H_Z maps to NSLC: 'IU', 'ANMO', '', 'BHZ'
Temporary network starting in 2002 XFDSN:XA_ABCD_00_B_H_Z maps to NSLC: 'XA', 'ABCD', '00', 'BHZ'
Temporary network starting in 2002 XFDSN:XA2002_ABCD_00_B_H_Z maps to NSLC: 'XA', 'ABCD', '00', 'BHZ'

**Comment by chad-earthscope** [comment]
Added to docs with a lot of formatting and some editing, needs checking.

**Comment by chad-earthscope** [comment]
The description for mapping network codes from NSLC to SID concern me a bit.

```
Network codes

Codes the 1-2 character network code is mapped unchanged.

For temporary networks, starting with X, Y, Z or 0-9, the 2 character network code may be mapped either
unchanged, or may follow the “Transitional mapping of previously allocated temporary network codes” by
appending the start year to create a 6 character code.
```

One must have a clear understanding about the "Transitional mapping" to know that the codes must be allocated.  I would really like to add ", when the 6-character code has been allocated by the FDSN." to the end of the last sentence to clarify this point.

**Comment by crotwell** [comment]
I guess it might have to be done outside of this spec, but could the FDSN (or we as the FDSN) proactively allocate all the existing temp codes? And set up a system for any new 2 char temp network code requests to automatically trigger the 6-char allocation? In other words, it is automatic instead of opt-in?

**Comment by chad-earthscope** [comment]
Sure, but pre-allocation is the easy part.  There should only be one DOI, so we'd need to think through to which version it gets attached, and which are aliases.  We would need to discuss, agree and build an aliasing system for network codes.    There is no assurance that any data center would support aliases.  We might be able to work through these things, but for now it is not obvious to me that these will ever be universally interchangeable, and we shouldn't imply such a thing (yet).

**Comment by crotwell** [comment]
Fair enough.

**Comment by chad-earthscope** [comment]
The whole network paradigm is going to need a shift a bit and some new business rules adopted.  Currently, when requesting a code, an operator must choose between permanent and temporary code request.  What we'll need instead is a choice between:

1) legacy-compatible temporary network code in <2-character code><4-digit start year> pattern

and

2) everything else; limited to 1-8 characters, excluding the 6-character patterns of #1 and 2-character codes starting in [XYZ0-9].  With a note about only 1-2 characters being legacy compatible.

On further consideration, I'm starting to come around to a simpler view.  In actual allocation/display of temporary networks codes we never represent them without a start year due to re-use.  So maybe it's as straightforward as agreeing that the FDSN will start allocating XXYYYY codes for temporary networks and state that the XX part may be used in legacy formats where the full code is not possible.  No "official" aliases.  Also, no clear way for already allocated codes to use the new, longer codes, that's probably for the best anyway.  Hmmm, will still take some thought.

**Comment by crotwell** [comment]
+1

...and I suspect that no one will do anything other than the first option for quite some time given limitations of existing software and waveform file formats.
