### ISSUE TITLE
Position code in channel identifiers

### ISSUE THREAD

**Issue by flofux** [FDSN/source-identifiers#13]
When reading the doc I was very confused by calling the last letter in the channel scheme "Position". I guess that's because I'm (we are?) a seismologist and not used to this letter being anything but orientation. Also, for instrument types (e.g. pressure sensors), this letter has some implication for the sensor type (infrasound vs. hydrophone for example).

Thus my suggestion: Can we find another definition rather than "Position" for this letter? "Position/Orientation" doesn't seem very elegant though ... and still does not 100% fit for some sensor types.

Any suggestions?

**Comment by crotwell** [comment]
I agree it is a little confusing for sources that don't have obvious orientation or position concepts. It actually acts more as a "source sub-identifier" where the meaning is always relative to the given source. That said, I am not sure I have a better word for it.

**Comment by chad-earthscope** [comment]
I'm not fond of "Position" and am happy for any better suggestions as long as they are short and can be used in SID construction documentation concisely (not "Position/Orientation" 😆).

It really is a "SubSource".  (as terrible as that sounds).

**Comment by crotwell** [comment]
Subsource at least gives the correct meaning. Wish there was a better word, but I like subsource better than proition. Something like:

Subsource: Identifies a sub-category within the source, often the orientation or otherwise relative position. The meaning of subsource codes are specific to the containing source. May be empty.

**Comment by flofux** [comment]
I'd agree with "Subsource" and I like your description!

**Comment by WayneCrawford** [comment]
I would add "sensor type" to "orientation or relative position", as you already pointed out for pressure sensors.
