### ISSUE TITLE
Channel naming 1,2,3 for seismometers

### ISSUE THREAD

**Issue by flofux** [FDSN/source-identifiers#15]
As this documentation will be the new main guideline for channel naming, I'd suggest to expand the explanation for seismometer channels that are not Z,N,E or should not be Z,N,E because this sometimes creates confusion/mess. We state that channels should be named Z,N,E when within 5 degrees of true N/E, but maybe we should add what to do if it's not. Let's be clear about whether the naming scheme should be 1,2,3 or Z,1,2 or Z,2,3. I vote for Z,2,3 as I think 1 should be reserved for a somewhat vertical component. Both Z,1,2 and Z,2,3 are currently in use, so either way we will break consistency in some cases.

I'd suggest to expand the description of 1,2,3 channels like this (or similar):

> Orthogonal components but non traditional orientations. If the orientation of the horizontal components is known to deviate more than 5 degrees from true North/East, the respective channels should be named 2,3 instead of N,E (N->2, E->3).

In the field for Z,N,E channels it could be (or similar):

> Traditional (Vertical, North-South, East-West), when WITHIN 5 degrees of true directions. Do not use N or E labels if the orientation of the horizontal components is known to deviate more than 5 degrees from true North/East.

**Comment by chad-earthscope** [comment]
I agree, stronger wording in for this issue would be much better and documenting a common pattern very useful.

I would lean towards Z,1,2 due popularity (in the IRIS holdings) over Z,2,3.  The counts of combinations at IRIS:

{1,2,Z} = 15461  <- the highest channel set count for number and Z combinations
{2,3,Z} = 617

Interestingly also high:
{1,2,3} = 4394

**Comment by crotwell** [comment]
Might also be helpful to give names in terms of a right handed xyz coordinate system relative to the seismometer. For some reason I get confused on that easily. 

I think Z12 means 1 is in the seismometer's "y" direction and 2 is in the seismometer's "x" direction, which ends up being a left handed coordinate system, but...

**Comment by WayneCrawford** [comment]
For OBSs we have been using "Z12", based on IRIS precedent.  Then, when we figured out that many of our short period OBS (geophone) vertical components were inverted, we went to "312" (can also be read as '123', but the important thing is that the "3" channel is the vertical).  Don't know of a better solution, if you have one I'm game.  It's good to have a convention to simplify processing but, in any case, once we're off of "ZNE" the the metadata should include the dip and azimuth, which is the true reference.

**Comment by WayneCrawford** [comment]
We stopped using "x" and "y" when we figured out that Germans and French seem to use different handed coordinate systems: in France we associate "x" with "E" whereas in Germany they associated it with "N".  Caused all sorts of problems when trying to determine OBS orientations using EQ arrivals!

So I would say that "1" corresponds to "N" and "2" to "E", when the seismometer is properly oriented.

_______________________________
Wayne Crawford
CNRS Researcher
Institut de Physique du Globe de Paris
1, rue Jussieu
75238 Paris Cedex 05
+33 6 5151 1054

On 16 July 2020 at 21:30:28, Philip Crotwell (notifications@github.com) wrote:

Might also be helpful to give names in terms of a right handed xyz coordinate system relative to the seismometer. For some reason I get confused on that easily.

I think Z12 means 1 is in the seismometer's "y" direction and 2 is in the seismometer's "x" direction, which ends up being a left handed coordinate system, but...

**Comment by crotwell** [comment]
Yikes, I thought that xyz was universal! :( But I guess names are always subject to local language and custom. 

+1 for your version.
Maybe change "when the seismometer is properly oriented" to "when the seismometer is oriented to align with the traditional vertical-north-east coordinate system", just to be really clear?

I agree the metadata should be the real authority, but at least nice to have a naming convention that has some logic to it.

**Comment by crotwell** [comment]
This might not be a sentence. Was that meant to be a subheading?

> Orthogonal components but non traditional orientations.


Also, just question, should 1 and 2 imply horizontal in general? Or is the implication only the other way?

Is it worth adding at end something about orthogonal but not vertical-horizontal orientations? Maybe like:

Orthogonal components that are not vertical and horizontal, e.g. along the edges of a cube turned up on a corner, should use A,B,C or U,V,W. Components with other orientations may use any remaining valid subsource codes.

**Comment by chad-earthscope** [comment]
> Also, just question, should 1 and 2 imply horizontal in general? Or is the implication only the other way?

I would think we should go for as much consistency as possible.  I changed the table for seismometers (http://docs.fdsn.org/projects/source-identifiers/en/draft/channel-codes.html#seismometer) to have them in a 3,1,2 order FWIW.

**Comment by chad-earthscope** [comment]
> Is it worth adding at end something about orthogonal but not vertical-horizontal orientations? Maybe like:

That is touched on in the seismometer specific details.

**Comment by chad-earthscope** [comment]
> This might not be a sentence. Was that meant to be a subheading?
> 
> > Orthogonal components but non traditional orientations.

I've fixed that grammar I believe.

If we want to specifically mention a mapping for "Z" let me know.

**Comment by crotwell** [comment]
Looks good to me.

**Comment by chad-earthscope** [comment]
Are we done with this one?

**Comment by crotwell** [comment]
Can we add a line for Z12, like in the J source section? As that is very common and is not in the table. Like:

`Z, 1, 2 | Orthogonal components, but non traditional horizontal orientations`

**Comment by chad-earthscope** [comment]
Done in e1743f2c9d0cda7314eda058b6ed56252f18e9ab
