### ISSUE TITLE
Time in source identifiers

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#16]
Not sure if this needs addressing within the spec, but...

The spec says near the beginning:

"The FDSN defines, allocates and adopts a number of codes that, when combined in a hierarchy, uniquely identify a data source."

but of course the codes don't uniquely identify anything without a time to go along with it.

So, is it worth adding verbage along the lines of
"uniquely identify a data source at a given time."? 

Not sure this really matters and is probably well known, but maybe it is worth making explicit the idea that codes are reused and therefore the data source connected with a URI might change with time? Leaving things as assumptions often comes back to bite you.

**Comment by chad-earthscope** [comment]
> So, is it worth adding verbage along the lines of
> "uniquely identify a data source at a given time."?

I'm fine adding that to make it correct.
