### ISSUE TITLE
move source code P, Geophone, into seismometer catagory

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#18]
Geophone is a type of seismometer, so would be clearer if it were grouped with the H, L, N... source codes. This also puts the orientation sub-source information in one place. Otherwise it needs to be repeated for the geophone. Currently it only has ZNE.

Propose add:
```
P | Geophone
```
to the seismometer table and remove existing geophone section.

**Comment by chad-earthscope** [comment]
Yup.  I agree.

**Comment by chad-earthscope** [comment]
Done in 7dbb1330a2a98f72de0543d949db13eabf402eca.

I also moved Gravimeter (G) out of the seismometer section, I think it was only there for historical purposes as a use for accelerometer.
