### ISSUE TITLE
small typos

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#21]
Found just a couple of small items, not really worth making an issue for but...

### In network code part of S.I to NSLC, this sentence is little awkward and extra space before the comma.

> Network codes following the 6-character “Temporary network codes convention”, can be mapped , the first 2 
> characters of the network code mapped to the NSLC network code by removing the 4 character year.

Suggest something like:

> Network codes following the 6-character “Temporary network codes convention” are mapped using just the first 2 
> characters of the network code, e.g. removing the 4 character year.

### Location Code section, should be 2 chars:  

> Codes between 0 and 1 characters are mapped unchanged.

should be  

> Codes between 0 and 2 characters are  mapped unchanged.

### Channel Code section:  

> Otherwise, there is no mapping when individual codes greater than 2 characters.

should be  

> Otherwise, there is no mapping when individual codes are greater than 2 characters.

### Possible change  

> Codes between 1 to 5

to  

> Codes from 1 to 5

to avoid possible "does this mean 2,3,4 or 1,2,3,4,5? Small issue, no strong opinion, just trying to look for any ambiguity.

### Magnetometer section 
looks like there is an extra newline in output between "field" and "vector" making it look like another paragraph?

**Comment by chad-earthscope** [comment]
Thanks.  I've applied and cleaned this section up further.

Eventually here:
http://docs.fdsn.org/projects/source-identifiers/en/draft/definition.html#mapping-of-seed-2-4-codes
