### ISSUE TITLE
rotational sensor

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#22]
Currently, as well as in the SEED manual, says:
```
Source Code
J - High Gain Seismometer
```

I suspect this is a bad copy/paste from long  long ago. It should just say:
```
Source Code
J
```

**Comment by chad-earthscope** [comment]
FWIW, I think they are high gain rotational seismometers.  I'm not sure there will ever be low gain ones, nor any reason to split this definition, so I agree with your edit.

**Comment by chad-earthscope** [comment]
Done in b4ef47c314183d03b55c6ad1fde8cd27b71c94be
Changed to "Rotation rate sensor" as used on http://www.rotational-seismology.org/
