### ISSUE TITLE
Pressure sensors

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/source-identifiers#25]
I have a couple of comments/questions about pressure sensors, as they are very important for ocean-bottom seismometers.

First, should differential pressure gauges have their own subsource code?  IRIS currently uses "H" but these are not hydrophones.  I have used "F" in the past as their frequency band and technology is closer to that of an infrasound gauge, but this has not caught on and maybe rightly so, as they are not "sound" gauges

Second, I'm not sure that I agree that "dip" should not be specified for a pressure gauge (at least at the seafloor).  Ocean bottom seismometer pressure gauges (hydrophones or differential) have a specific polarity with respect to seismometer vertical channels (or perhaps more appropriately the longitudinal component).  The problem is that the polarity depends on the direction that the wave is propagating.  To facilitate processing, I have been specifying a dip that provides consistent polarity with a vertical channel for first arrivals (upgoing waves).

If "dip" is inappropriate for a pressure gauge (which I don't deny), there should at least be some way to express the gauge's polarity, indicating whether an increase in pressure corresponds to a positive or negative output.  Are negative gains allowed?  If so, this could work, but again one would need to define what positive/negative gains mean.

**Comment by crotwell** [comment]
+1 for adding a new subsource code. But maybe it should be a new source code as differential pressure sounds like it is different from just plain old pressure. 

@chad-iris I think prefers that requests for new source codes be done separately, but perhaps creating an issue for any new codes would be a good way to start? You get to come up with the code, all the 2 chars are open! :)

I don't think that lack of dip/azimuth guidance in the source code precludes putting dip/azimuth into metadata like stationxml, if it is meaningful for the channel. Probably instead of `Dip/Azimuth: Not applicable` it should say `Dip/Azimuth: Along axis of measurement if applicable, 0/0 otherwise`. Might be good to do that for all sources. 

In particular, Magnetometer (F) has a paragraph about dip and azimuth, but then says `Dip/Azimuth: Not applicable`.

**Comment by chad-earthscope** [comment]
> First, should differential pressure gauges have their own subsource code?

Sure, now's the time to add one.  Unfortunately 'D' is taken for down-hole.  Let me know which you'd like to add.

I'm happy to put something in for dip/azimuth if you need to use to to define polarity.  Can you suggest what to write here?

**Comment by WayneCrawford** [comment]
How about 'G'? It's in between "F" (infrasound) and "H" (hydrophone), like the sensor, and it's got the "G" for gauge, if you like stretching logic.

For Dip I would say: if the signal will be used for seismological applications, set Dip to -90 if a positive pressure change gives a positive signal, 90 if a positive pressure change gives a negative signal.  This will align polarities with the vertical seismometer channel for UPGOING waves.

**Comment by chad-earthscope** [comment]
@WayneCrawford Naive question: what kinds of sensors would the `G` subsource code represent?

Unless I'm mistaken, it is common for both microbarometers (infrasound) and hydrophones to be fundamentally be differential pressure sensors.  When I added the `G` code I wrote "Differential pressure gauge":

http://docs.fdsn.org/projects/source-identifiers/en/draft/channel-codes.html#pressure

but that seems too general a description.

**Comment by crotwell** [comment]
One more question to add to the mix, infrasound, and presumably other differential pressure sensors, measure pressure differences between two points, hence a line, hence they have orientation, hence you can have 3 components, hence you likely need 3, hence G as a subsource code is 2 short? 

Do differential pressure sensors need orientation, so the full X,Y,Z or Z,N,E or Z,1,2?

Guess this could be done as none of those are taken yet.

**Comment by WayneCrawford** [comment]
I haven't looked closely at the physics, but these sensors are generally comparing to a reference and so the orientation is not clear.  Hydrophones can have a directionality but they generally try to have a somewhat full-azimuth sensitivity and, in any case, flipping a hydrophone upside down will not flip its output polarity.  I think it's the same for differential pressure gauges and infrasound sensors. Or at least what I refer to as a differential pressure gauge, which is actually a Cox-Deaton-Webb differential pressure gauge (see attached article).  If there are differential pressure gauges that truly measure the difference between two (external) points, then were would need to be three codes for this, maybe the same as for seismometers etc?  We could also change the subsource code for the Cox-Deaton-Webb gauge to "C" (for Cox) if you'd like to keep "G" for a more general (but non-directional!) gauge.

Cheers
Wayne

_______________________________
Wayne Crawford
CNRS Researcher
Institut de Physique du Globe de Paris
1, rue Jussieu
75238 Paris Cedex 05
+33 6 5151 1054

On 14 September 2020 at 15:28:27, Philip Crotwell (notifications@github.com) wrote:

One more question to add to the mix, infrasound, and presumably other differential pressure sensors, measure pressure differences between two points, hence a line, hence they have orientation, hence you can have 3 components, hence you likely need 3, hence G as a subsource code is 2 short?

Do differential pressure sensors need orientation, so the full X,Y,Z or Z,N,E or Z,1,2?

Guess this could be done as none of those are taken yet.

**Comment by chad-earthscope** [comment]
My concern was that the description is "Differential pressure gauge" is broad, and other sensors like many e.g. microbarometers (e.g. https://asa.scitation.org/doi/abs/10.1121/1.3596718?journalCode=jas) would also match that description.

I'd prefer to specify something more generic than a specific instrument.  Would `G` - "Directional differential pressure gauge" be appropriate?

**Comment by chad-earthscope** [comment]
Changed the `G` subsource code description to "Deep sea differential pressure gauge" in 2e212d6cc60178822b3f66458f397df14a190775.
