### ISSUE TITLE
URN vs URI, fix link

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#28]
Couple small items:

The link to rfc3986 would be easier to get to if you append ".html" to it. Then it will open in the browser, and the table of contents has links. Otherwise you get an option to save it. Not sure why the ietf does that, it is annoying. So use:
```
https://www.ietf.org/rfc/rfc3986.html
```
instead of
```
https://www.ietf.org/rfc/rfc3986
```

Second, the rfc says:

> Future specifications and related documentation should
> use the general term "URI" rather than the more restrictive terms
>   "URL" and "URN" [RFC3305].

and so it might be better to just use URI and "identifier" instead of name in the spec.

**Comment by crotwell** [comment]
Also should delete this sentence since no longer using URN:

> The formal urn: URI scheme prefix is not included in source identifiers within FDSN formats.

**Comment by crotwell** [comment]
And this in the background section, change to URI:

> Specify a Uniform Resource Identifier (URN)-like string as a “source identifier” (SID)

**Comment by crotwell** [comment]
@chad-iris This [section](http://docs.fdsn.org/projects/source-identifiers/en/v1.0/definition.html#source-identifiers) still says "URN". Maybe switch to URI to be consistent with rest of spec?

> Source Identifiers
>
> The FDSN Source Identifier (SID) is a combination of the network, station, location, band, source and subsource codes into a Uniform Resource Name (URN) as defined by RFC 3986.

**Comment by chad-earthscope** [comment]
Done in ca5f9a1fa7dc2854032404f563431ccc1e55c46d
