### ISSUE TITLE
Refinement of Sphinx theme and layout

### ISSUE THREAD

**Issue by chad-earthscope** [FDSN/source-identifiers#3]
In the initial work I tried to configure the Sphinx Alabaster theme similarly to the fdsn.org styling.  I expect there will be further FDSN documentation created in Sphinx/reStructure text, and that this project will be used as a baseline.  It's worth trying to refine this templating for the general case that we use for multiple projects.  Any help would be appreciated.

**Comment by WayneCrawford** [comment]
No comment

**Comment by WayneCrawford** [comment]
That wasn't ironic, it just meant "no opinion"

**Comment by chad-earthscope** [comment]
Done.  For me at least.  Simple theme used by multiple emergent FDSN documentation projects.
