### ISSUE TITLE
Changes from Seed 2.4 page

### ISSUE THREAD

**Issue by flofux** [FDSN/source-identifiers#30]
We should probably add these changes to the manual page:

http://docs.fdsn.org/projects/source-identifiers/en/v1.0/background.html

* Specific sampling rate ranges for U, >= 0.01 to < 0.1, V, >= 0.1 to < 1, band codes. 
* Band code W added to fill the gap between U and R, >= 0.001 to < 0.01
* Band code J added for > 5000 sps.
* Band code I added for irregular sampling
* Band code A, O deprecated
* Source codes X, Y deprecated

**Comment by chad-earthscope** [comment]
Done in 281b4299812b95efa1037237ad1ea4aac78db49f

As usual it will take some time for the caches to refresh.
