### ISSUE TITLE
mapping lower case SEED?

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#33]
Just opening an issue so isn't lost, see https://github.com/FDSN/source-identifiers/pull/32#issuecomment-707949805

Source ids are limited to upper case and numbers.

SEED NSLC are upper and numbers and potentially **lower case**!?!?!?

Should the SEED to SID mapping accommodate lower case letters or prohibit them?

The spec says:

 >   A NSLC can always be mapped to a Source Identifier.

but this would not be the case if the SEED NSLC contained lower case letters?

**Comment by chad-earthscope** [comment]
> Should the SEED to SID mapping accommodate lower case letters or prohibit them?

Prohibit them, up-casing them is a change in identifier/code in SEED and it should be clear that this is not allowed in SourceIDs.

> The spec says:
> "A NSLC can always be mapped to a Source Identifier."
> but this would not be the case if the SEED NSLC contained lower case letters?

We can add "The only exception is the use of lower case letters in SEED, which are not allowed in this specification and have historically not been used in SEED." if you wish.

Given that there is no widespread use of lower case characters, I'm not too worried about this being an issue.  The only time I've seen them is in quirky conversations from other formats that happen to have lower case and were transient (not archived/exchanged) data.

**Comment by crotwell** [comment]
My only encounter with lower case is the default SOH channels from an Obsidian. You get weird channel names like 'deg' for the internal temperature, etc.

+1 on prohibiting.
