### ISSUE TITLE
Determine final location and build process for release documentation

### ISSUE THREAD

**Issue by chad-earthscope** [FDSN/source-identifiers#4]
There are a couple of options:

* Render the documentation in Sphinx manually and post to fdsn.org somewhere
* Render and push to GitHub Pages (can be automated with Actions)
* Set up readthedocs to build the documentation

First option is completely independent of a service, but otherwise is the worst option IMHO.
GitHub Pages is OK and we can use their CDN and a custom domain, e.g. docs.fdsn.org, but there is no built in support for versioning.
The readthedocs option is nearly ideal, with versioning and PDF building.  But that site contains ads, which can be reduced to non-commercial ads, but not turned out without paying.   Hmm.

**Comment by chad-earthscope** [comment]
Further note, the readthedocs Community option also allows a custom domain, e.g. docs.fdsn.org.  But it would include the ads as well.

**Comment by crotwell** [comment]
Specification approval is such a rare event that manual rendering and posting of pdf to the fdsn website seems reasonable to me. The expansion of approved channel source codes might be more frequent, but could be accommodated by referring to a separate document. Known 1 char codes would be listed here, but the spec could reference a fdsn web page for future approved codes much as network codes are currently maintained.

**Comment by chad-earthscope** [comment]
Done.  It will live here: http://docs.fdsn.org/projects/source-identifiers

Currently that location shows an older version of docs, but will become the same as this when changes are merged back into master: http://docs.fdsn.org/projects/source-identifiers/en/draft/
