### ISSUE TITLE
wind speed

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#6]
copy from https://github.com/iris-edu/xseed-specification/issues/15

> Apparently wind speed is sometimes measured as a horizontal speed and a vertical speed. It might be useful to have orientation codes for these in addition to the existing S for speed. Perhaps H for horizontal speed and Z for vertical speed.

**Comment by flofux** [comment]
Yes, could it follow the same naming as seismic channels? like x_S_Z? Sounds reasonable to me.

**Comment by WayneCrawford** [comment]
No opinion

**Comment by crotwell** [comment]
Propose add:
```
H | Horizontal wind speed
Z | Vertical wind speed
```
to the W source position section.
