### ISSUE TITLE
Add clarity re: the transitional mapping of previously allocated temporary network codes 

### ISSUE THREAD

**Issue by chad-earthscope** [FDSN/source-identifiers#8]
From W. Crawford:
> Some temporary codes end with a number, which could result in "confusing" codes such as Z12010.   That wouldn't confuse anyone if 6-character codes always end with the 4-character year, the specification just needs to be very clear about this.

**Comment by crotwell** [comment]
My feeling is that the mapping is primarily to give a globally unique 6 char network code to all temporary networks and preventing collisions, not to provide a way to get the start time of the network. That is best retrieved from the metadata. In other words, while Z12010 should be the long network code for the Z1 temporary network that started in 2010,  there is no expectation or requirement that network AB2010 started in the year 2010.

**Comment by chad-earthscope** [comment]
I agree that the mapping is primarily concerned with uniqueness of the code.   Deployment start year is convenient to have included, but currently not required (left at "strongly encouraged").

The issue I see to be considered is some guideline/rule to avoid allocation of `XY2010` that is _not_ associated with the `XY` allocation in 2010.  This may be as simple as a rule that 6-character network codes starting with [XYZ0-9] and ending with 4 digits will not be allocated without a matching 2-character code, which would essentially bar the any allocation in the transitional mapping space.

**Comment by crotwell** [comment]
Yes, agree, issue #9

**Comment by flofux** [comment]
Any particular reason to not allow the dash "-" symbol in network codes? This could easily be used to highlight the year: SEIS-2018, Z1-2010 ...

**Comment by WayneCrawford** [comment]
Nothing to add beyond my initial comment, which was well answered in my opinion
