### ISSUE TITLE
reserve network codes that match temp network mapping pattern

### ISSUE THREAD

**Issue by crotwell** [FDSN/source-identifiers#9]
This probably does not need to be part of this specification, so just creating this issue as a reminder.

The FDSN should proactively reserve all 6 char strings that look like 
`<2 char temp code><4 digit year>` 
so that there are not collisions. So the XA network that started in 2020 should by default receive the XA2020 long code, and another network that just wanted to be called XA2020 should not be allowed.

Once (if) this scheme becomes widely adopted, the distinction between permanent and temporary networks more or less goes away and new networks of either type can choose network codes that best suit them.

**Comment by crotwell** [comment]
Attached is a list of current temporary network (matching `[0-9XYZ].`) and the 6 digit network code `<2char><startyear>` that should be reserved for each. It is possible more temporary network codes will be issues in the future, but certanily all of these should be reserved by the FDSN.

Also, really simple python script to generate the list:
```
import json
import re

pat = re.compile('[0-9XYZ].')

# get all networks as json from FDSN with:
# curl -o fdsnNetworks.json 'http://www.fdsn.org/ws/networks/1/query'

with open('fdsnNetworks.json') as f:
    fdsn = json.load(f)
    print('NetworkCode 2CharCode StartDate EndDate Name DOI')
    for n in fdsn['networks']:
        if pat.match(n['fdsn_code']):
            print(f'{n["fdsn_code"]}{n["start_date"][:4]} {n["fdsn_code"]} {n["start_date"]} {n["end_date"]} {n["name"]} doi:{n["doi"]}')

```

[reserved_network_codes.txt](https://github.com/iris-edu/xFDSN-source-identifiers/files/4703663/reserved_network_codes.txt)

**Comment by chad-earthscope** [comment]
> The FDSN should proactively reserve all 6 char strings that look like...

I agree and that was the idea.  If you can come up with some wording I can use that'd be great.

**Comment by crotwell** [comment]
How about change the last paragraph in the Transitional Mapping section to:

> A temporary network operator may wish to request a 6 character network code in the transitional mapping pattern above in order have a globally unique code that is also usable with miniSEED 2 through the mapping. Furthermore, the FDSN must reserve all 6 character network codes that match the transitional mapping pattern for all previously or future allocated 2 character temporary network codes. Thus the code XA2002 must be assigned solely to the temporary network with code XA that was operating in 2002.

**Comment by flofux** [comment]
Sounds good to me.

**Comment by WayneCrawford** [comment]
Me too

**Comment by chad-earthscope** [comment]
I changed 

```Furthermore, the FDSN must reserve all 6 character network codes...```
to
```Furthermore, the FDSN reserves all 6 character network...```

So we speak as the FDSN and not "to" it.
